In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

concat 과정에서 컬럼명이 들어간 행이 하나 추가되어서 엑셀에서 삭제하였음

# 가구/개인 여행 컬럼 통일

In [ ]:
최종병합 = pd.read_csv('C:/Users/user/Desktop/kdata/프로젝트/최종병합.csv', encoding='cp949')

In [599]:
# q5_2 (동행한 사람과의 관계 / 그 외 동행자 유형) -> 개인여행 기준으로 응답 통일
# q5_2_4가 가구 여행에서는 기타 유형의 동행자인데, 개인 여행 기준으로 컬럼을 통합해서 비동거가족 동행자가 됨
# 이것을 다시 기타 유형으로 바꿔줌
# q5_2_4(비동거가족), q5_2_5(친척)는 null로 채워줌

최종병합.loc[최종병합['가구/개인여행'] == 1, '동행한 사람과의 관계_기타'] \n
= 최종병합.loc[최종병합['가구/개인여행'] == 1, '동행한 사람과의 관계_비동거가족']

In [600]:
최종병합.loc[최종병합['가구/개인여행'] == 1, '동행한 사람과의 관계_비동거가족'] = np.nan
최종병합.loc[최종병합['가구/개인여행'] == 1, '동행한 사람과의 관계_친척'] = np.nan

In [601]:
최종병합.loc[최종병합['가구/개인여행'] == 1, '동행한 사람과의 관계_기타'].value_counts()

6.0    252
4.0    117
Name: 동행한 사람과의 관계_기타, dtype: int64

In [7]:
# 가구여행; q5_a-c (동반자 수) / 개인여행: q5_1(본인을 제외한 함께 여행한 일행 수)
# -> 동반자수 a-c의 합을 함께 여행한 일행 수에 추가, 동반자수 a-c 삭제

최종병합.loc[최종병합['가구/개인여행'] == 1, '본인을 제외한 함께 여행한 일행 수'] \
= 최종병합['동반자 수_동거 가족이나 친척'] + 최종병합['동반자 수_비동거 가족이나 친척'] + 최종병합['동반자 수_그 외 동행자']

최종병합.drop(['동반자 수_동거 가족이나 친척', '동반자 수_비동거 가족이나 친척', '동반자 수_그 외 동행자'], 
          axis = 1, 
          inplace = True)

In [9]:
# 가구여행: x / 개인여행: 함께 여행한 일행 존재 여부 
# -> 가구여행은 가구원이 함께 여행하였으므로 존재함을 나타내는 값(1)을 입력 

최종병합.loc[최종병합['가구/개인여행'] == 1, '함께 여행한 일행 존재 여부'] = 1

In [12]:
최종병합.to_csv('C:/Users/user/Desktop/kdata/프로젝트/최종병합.csv', encoding='cp949')

# 불필요한 컬럼 삭제 (by 동욱)

동욱님이 입력하신 컬럼명과 병합데이터의 컬럼 명이 달라서 엑셀에서 데이터의 컬럼명을 수정하였음

In [16]:
최종병합 = pd.read_csv('C:/Users/user/Desktop/kdata/프로젝트/최종병합.csv', encoding='cp949')

In [17]:
# [제외 컬럼 명]
# '여행 월', '여행 도착 월', '여행 도착 일', '여행 일',
# '참고한 인터넷 사이트 1순위', '참고한 인터넷 사이트 2순위' : 2167개 데이터만 존재함
# '구매한 여행상품': 1232개
# '단체회비/단체경비에 여행상품 구매 비용 포함 여부': 5469개
# '가중치_x', '가중치_y'
# '여행한 광역시/도 내 시/군2~6(해외여행: 도시)'
# '여행지별 여행일수'
# '숙박시설 별 숙박 박수 호텔' 등등
# '여행지에서 지출비용'

# '사전예약을 한 서비스 00'
# '구매한 여행상품' 관련 컬럼

# [비고]
# 값 없는 data 처리하기
# '여행지 선택이유 3순위': 없는 data 존재

최종병합_sub = 최종병합[['gubun', '가구번호', '가구원번호', '매칭 ID', '당일/숙박여행 여부',
                     '여행 출발 월', '여행 출발 일', '여행 박', '여행 시기 주중', '여행 시기 주말',
                     '여행 시기 휴가/방학', '여행 시기 설날/추석', '여행 시기 공휴일',
                     '여행 주 목적', '여행 정보 주요 획득지 1순위',
                     '여행 정보 주요 획득지 2순위', '함께 여행한 일행 존재 여부', '본인을 제외한 함께 여행한 일행 수',
                     '동행한 사람과의 관계 친구/연인', 
                     '동행한 사람과의 관계 (직장)동료', '동행한 사람과의 관계 단체/모임', 
                     '동행한 사람과의 관계 비동거가족', '동행한 사람과의 관계 친척',
                     '동행한 사람과의 관계 기타',
                     '총 지출비용', '사전 지출비용', '단체비용', '여행사 상품구입비', '숙박비', '교통비', '식/음료비',
                     '문화/오락시설 이용료/관람료', '스포츠/레포츠 용품대여/구입비, 경기관람료', '기념품 및 쇼핑비',
                     '여행지에서 여행관련용품 구입비', '기타비용', '여행 출발 전 사전예약을 통해 이용한 서비스 여부',
                     '여행상품 구매 또는 이용 여부', '항목별 만족도 자연경관', '항목별 만족도 문화유산',
                     '항목별 만족도 교통', '항목별 만족도 숙박시설', '항목별 만족도 식당 및 음식', '항목별 만족도 쇼핑',
                     '항목별 만족도 관광정보 및 안내시설', '항목별 만족도 관광지 편의시설',
                     '항목별 만족도 지역 관광종사자의 친절성', '항목별 만족도 체험프로그램',
                     '항목별 만족도 관광지 물가', '항목별 만족도 관광지 혼잡도', '여행한 광역시/도(해외여행: 국가)',
                     '여행한 광역시/도 내 시/군1(해외여행: 도시)', '여행지 선택이유 1순위', '여행지 선택이유 2순위',
                     '여행지 선택이유 3순위', '주요 이동(교통)수단', '전반적 만족도', '재방문 의향', '타인 추천의향',
                     '숙박시설 숙박하지 않음', '숙박시설 호텔', '숙박시설 콘도미니엄', '숙박시설 유스호스텔',
                     '숙박시설 모텔/여관', '숙박시설 펜션', '숙박시설 민박', '숙박시설 야영', 
                     '숙박시설 자연휴양림 내 숙박시설', '숙박시설 가족/친지집', '숙박시설 연수원/수련원',
                     '숙박시설 전통한옥숙박시설', '숙박시설 기타','여행지에서의 활동 자연 및 풍경 감상',
                     '여행지에서의 활동 음식관광', '여행지에서의 활동 야외 위락 및 스포츠 활동',
                     '여행지에서의 활동 역사유적지 방문', '여행지에서의 활동 테마파크, 놀이시설, 동/식물원 방문',
                     '여행지에서의 활동 휴식/휴양', '여행지에서의 활동 온천/스파', '여행지에서의 활동 쇼핑',
                     '여행지에서의 활동 지역 문화예술/공연/전시시설 관람', '여행지에서의 활동 스포츠 경기 관람',
                     '여행지에서의 활동 지역 축제/이벤트 참가', '여행지에서의 활동 교육/체험프로그램 참가',
                     '여행지에서의 활동 종교/성지순례', '여행지에서의 활동 갬블링', '여행지에서의 활동 시티투어',
                     '여행지에서의 활동 드라마 촬영지 방문', '여행지에서의 활동 가족/친지/친구 방문',
                     '여행지에서의 활동 회의참가/시찰', '여행지에서의 활동 교육/훈련/연수', 
                     '여행지에서의 활동 유흥/오락', '여행지에서의 활동 기타'
                     ]]

In [18]:
# '여행 시기 주중', '여행 시기 주말', '여행 시기 휴가/방학', '여행 시기 설날/추석', '여행 시기 공휴일'
# NaN값 제거한 뒤에 0, 1로 바꿔서 전처리

최종병합_sub.iloc[:, 8:13]

       여행 시기 주중  여행 시기 주말  여행 시기 휴가/방학  여행 시기 설날/추석  여행 시기 공휴일
0           1.0       NaN          NaN          NaN        NaN
1           1.0       NaN          NaN          NaN        NaN
2           1.0       NaN          NaN          NaN        NaN
3           NaN       2.0          NaN          NaN        NaN
4           1.0       NaN          NaN          NaN        NaN
5           1.0       NaN          NaN          NaN        NaN
6           1.0       NaN          NaN          NaN        NaN
7           NaN       2.0          NaN          NaN        NaN
8           1.0       NaN          NaN          NaN        NaN
9           1.0       NaN          NaN          NaN        NaN
10          1.0       2.0          NaN          NaN        NaN
11          NaN       2.0          NaN          NaN        NaN
12          1.0       2.0          NaN          NaN        NaN
13          1.0       NaN          NaN          NaN        NaN
14          1.0       NaN          NaN          NaN        NaN
15          1.0       NaN          NaN          NaN        5.0
16          1.0       NaN          NaN          NaN        NaN
17          1.0       NaN          NaN          NaN        NaN
18          1.0       2.0          NaN          NaN        NaN
19          NaN       2.0          NaN          NaN        NaN
20          NaN       2.0          NaN          NaN        5.0
21          1.0       NaN          3.0          NaN        NaN
22          1.0       NaN          3.0          NaN        NaN
23          1.0       2.0          NaN          NaN        NaN
24          1.0       2.0          NaN          NaN        NaN
25          1.0       NaN          NaN          NaN        NaN
26          1.0       2.0          NaN          NaN        5.0
27          1.0       NaN          NaN          NaN        NaN
28          NaN       2.0          NaN          NaN        NaN
29          1.0       2.0          NaN          NaN        5.0
...         ...       ...          ...          ...        ...
51497       NaN       2.0          NaN          NaN        NaN
51498       NaN       2.0          NaN          NaN        NaN
51499       NaN       2.0          NaN          NaN        NaN
51500       NaN       2.0          NaN          NaN        NaN
51501       NaN       2.0          NaN          NaN        NaN
51502       NaN       2.0          NaN          NaN        NaN
51503       1.0       2.0          NaN          NaN        NaN
51504       NaN       2.0          NaN          4.0        NaN
51505       NaN       2.0          NaN          4.0        NaN
51506       NaN       2.0          NaN          NaN        NaN
51507       NaN       2.0          NaN          NaN        NaN
51508       1.0       2.0          NaN          NaN        NaN
51509       NaN       2.0          NaN          NaN        NaN
51510       NaN       2.0          NaN          NaN        NaN
51511       NaN       2.0          NaN          NaN        NaN
51512       NaN       2.0          NaN          NaN        NaN
51513       NaN       2.0          NaN          NaN        NaN
51514       1.0       2.0          NaN          NaN        NaN
51515       NaN       2.0          NaN          NaN        NaN
51516       NaN       2.0          NaN          NaN        NaN
51517       NaN       2.0          NaN          NaN        NaN
51518       NaN       2.0          NaN          NaN        NaN
51519       1.0       NaN          NaN          NaN        NaN
51520       1.0       2.0          3.0          NaN        5.0
51521       1.0       2.0          3.0          NaN        5.0
51522       1.0       2.0          NaN          NaN        NaN
51523       1.0       NaN          NaN          NaN        NaN
51524       NaN       2.0          NaN          NaN        NaN
51525       NaN       2.0          NaN          NaN        5.0
51526       NaN       2.0          NaN          NaN        5.0

[51527 rows x 5 columns]

In [19]:
def get_preprocessed_df(df):
    df_copy = df.copy()
    stays = list(df_copy.columns)
    for stay in stays:
        df_copy[stay] = df_copy[stay].apply(lambda x: 1 if x>0 else 0)
    return df_copy

In [20]:
최종병합_sub.iloc[:, 8:13] = get_preprocessed_df(최종병합_sub.iloc[:, 8:13])

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [21]:
최종병합_sub.reset_index(inplace=True)

In [22]:
최종병합_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51527 entries, 0 to 51526
Data columns (total 94 columns):
index                             51527 non-null int64
gubun                             51527 non-null int64
가구번호                              51527 non-null int64
가구원번호                             51527 non-null int64
매칭 ID                             51527 non-null int64
당일/숙박여행 여부                        51527 non-null int64
여행 출발 월                           51527 non-null int64
여행 출발 일                           51527 non-null int64
여행 박                              51527 non-null int64
여행 시기 주중                          51527 non-null int64
여행 시기 주말                          51527 non-null int64
여행 시기 휴가/방학                       51527 non-null int64
여행 시기 설날/추석                       51527 non-null int64
여행 시기 공휴일                         51527 non-null int64
여행 주 목적                           51527 non-null int64
여행 정보 주요 획득지 1순위                  51527 non-null int64
여행 정보 주요 획득지 2순위                  44398 non-null float64
함께 여행한 일행 존재 여부                   51527 non-null int64
본인을 제외한 함께 여행한 일행 수               51527 non-null int64
동행한 사람과의 관계 친구/연인                 14584 non-null float64
동행한 사람과의 관계 (직장)동료                1162 non-null float64
동행한 사람과의 관계 단체/모임                 6655 non-null float64
동행한 사람과의 관계 비동거가족                 1357 non-null float64
동행한 사람과의 관계 친척                    193 non-null float64
동행한 사람과의 관계 기타                    607 non-null float64
총 지출비용                            51527 non-null int64
사전 지출비용                           51527 non-null int64
단체비용                              26029 non-null float64
여행사 상품구입비                         51527 non-null int64
숙박비                               51527 non-null int64
교통비                               51527 non-null int64
식/음료비                             51527 non-null int64
문화/오락시설 이용료/관람료                   51527 non-null int64
스포츠/레포츠 용품대여/구입비, 경기관람료           51527 non-null int64
기념품 및 쇼핑비                         51527 non-null int64
여행지에서 여행관련용품 구입비                  51527 non-null int64
기타비용                              51527 non-null int64
여행 출발 전 사전예약을 통해 이용한 서비스 여부       51527 non-null int64
여행상품 구매 또는 이용 여부                  51527 non-null int64
항목별 만족도 자연경관                      51527 non-null int64
항목별 만족도 문화유산                      51526 non-null float64
항목별 만족도 교통                        51527 non-null int64
항목별 만족도 숙박시설                      41605 non-null float64
항목별 만족도 식당 및 음식                   51527 non-null int64
항목별 만족도 쇼핑                        51525 non-null float64
항목별 만족도 관광정보 및 안내시설               51527 non-null int64
항목별 만족도 관광지 편의시설                  51527 non-null int64
항목별 만족도 지역 관광종사자의 친절성             51527 non-null int64
항목별 만족도 체험프로그램                    51527 non-null int64
항목별 만족도 관광지 물가                    51527 non-null int64
항목별 만족도 관광지 혼잡도                   51527 non-null int64
여행한 광역시/도(해외여행: 국가)               51527 non-null int64
여행한 광역시/도 내 시/군1(해외여행: 도시)        51527 non-null int64
여행지 선택이유 1순위                      51527 non-null int64
여행지 선택이유 2순위                      51178 non-null float64
여행지 선택이유 3순위                      50845 non-null float64
주요 이동(교통)수단                       51527 non-null int64
전반적 만족도                           51527 non-null int64
재방문 의향                            51527 non-null int64
타인 추천의향                           51527 non-null int64
숙박시설 숙박하지 않음                      30235 non-null float64
숙박시설 호텔                           2490 non-null float64
숙박시설 콘도미니엄                        3296 non-null float64
숙박시설 유스호스텔                        335 non-null float64
숙박시설 모텔/여관                        1878 non-null float64
숙박시설 펜션                           6678 non-null float64
숙박시설 민박                           1304 non-null float64
숙박시설 야영                           1190 non-null float64
숙박시설 자연휴양림 내 숙박시설                 347 non-null float64
숙박시설 가족/친지집                       2163 non-null float64
숙박시설 연수원/수련원                      630 non-null float64
숙박시설 전통한옥숙박시설                     87 non-null float64
숙박시설 기타                           1079 non-null float64
여행지에서의 활동 자연 및 풍경 감상              41633 non-null float64
여행지에서의 활동 음식관광                    29167 non-null float64
여행지에서의 활동 야외 위락 및 스포츠 활동          16603 non-null float64
여행지에서의 활동 역사유적지 방문                6689 non-null float64
여행지에서의 활동 테마파크, 놀이시설, 동/식물원 방문    6588 non-null float64
여행지에서의 활동 휴식/휴양                   21131 non-null float64
여행지에서의 활동 온천/스파                   1994 non-null float64
여행지에서의 활동 쇼핑                      2588 non-null float64
여행지에서의 활동 지역 문화예술/공연/전시시설 관람      3821 non-null float64
여행지에서의 활동 스포츠 경기 관람               797 non-null float64
여행지에서의 활동 지역 축제/이벤트 참가            2643 non-null float64
여행지에서의 활동 교육/체험프로그램 참가            1522 non-null float64
여행지에서의 활동 종교/성지순례                 1896 non-null float64
여행지에서의 활동 갬블링                     21 non-null float64
여행지에서의 활동 시티투어                    422 non-null float64
여행지에서의 활동 드라마 촬영지 방문              525 non-null float64
여행지에서의 활동 가족/친지/친구 방문             2139 non-null float64
여행지에서의 활동 회의참가/시찰                 98 non-null float64
여행지에서의 활동 교육/훈련/연수                279 non-null float64
여행지에서의 활동 유흥/오락                   1519 non-null float64
여행지에서의 활동 기타                      2132 non-null float64
dtypes: float64(47), int64(47)
memory usage: 37.0 MB

In [23]:
# '동행한 사람과의 관계 친구/연인':'동행한 사람과의 관계 기타'
# NaN값 제거한 뒤에 0, 1로 바꿔서 전처리

최종병합_sub.loc[:, '동행한 사람과의 관계 친구/연인':'동행한 사람과의 관계 기타']

,동행한 사람과의 관계 친구/연인,동행한 사람과의 관계 (직장)동료,동행한 사람과의 관계 단체/모임,동행한 사람과의 관계 비동거가족,동행한 사람과의 관계 친척,동행한 사람과의 관계 기타
0,1.0,NaN,NaN,NaN,NaN,NaN
1,1.0,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,3.0,NaN,NaN,NaN
4,NaN,NaN,3.0,NaN,NaN,NaN
5,NaN,NaN,3.0,NaN,NaN,NaN
6,NaN,NaN,3.0,NaN,NaN,NaN
7,NaN,NaN,3.0,NaN,NaN,NaN
8,NaN,NaN,3.0,NaN,NaN,NaN
9,NaN,NaN,NaN,4.0,NaN,NaN
10,1.0,NaN,NaN,NaN,NaN,NaN
11,1.0,NaN,NaN,NaN,NaN,NaN
12,1.0,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,4.0,NaN,NaN
14,NaN,NaN,NaN,4.0,NaN,NaN
15,NaN,NaN,NaN,4.0,NaN,NaN
16,1.0,NaN,NaN,NaN,NaN,NaN
17,1.0,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,3.0,NaN,NaN,NaN
20,1.0,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,4.0,NaN,6.0
22,NaN,NaN,NaN,4.0,NaN,6.0
23,1.0,NaN,NaN,NaN,NaN,NaN
24,1.0,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN
27,1.0,NaN,NaN,NaN,NaN,NaN
28,1.0,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
51497,NaN,NaN,NaN,NaN,NaN,NaN
51498,NaN,NaN,NaN,NaN,NaN,NaN
51499,NaN,NaN,NaN,NaN,NaN,NaN
51500,NaN,NaN,NaN,NaN,NaN,NaN
51501,NaN,NaN,NaN,NaN,NaN,NaN
51502,NaN,NaN,NaN,NaN,NaN,NaN
51503,NaN,NaN,NaN,NaN,NaN,NaN
51504,NaN,NaN,NaN,NaN,NaN,NaN
51505,NaN,NaN,NaN,NaN,NaN,NaN
51506,NaN,NaN,NaN,NaN,NaN,NaN
51507,NaN,NaN,NaN,NaN,NaN,NaN
51508,NaN,NaN,NaN,NaN,NaN,NaN
51509,NaN,NaN,NaN,NaN,NaN,NaN
51510,NaN,NaN,NaN,NaN,NaN,NaN
51511,NaN,NaN,NaN,NaN,NaN,NaN
51512,NaN,NaN,NaN,NaN,NaN,NaN
51513,NaN,NaN,NaN,NaN,NaN,NaN
51514,NaN,NaN,NaN,NaN,NaN,NaN
51515,NaN,NaN,NaN,NaN,NaN,NaN
51516,NaN,NaN,NaN,NaN,NaN,NaN
51517,NaN,NaN,NaN,NaN,NaN,NaN
51518,NaN,NaN,NaN,NaN,NaN,NaN
51519,1.0,NaN,NaN,NaN,NaN,NaN
51520,NaN,NaN,NaN,NaN,NaN,NaN
51521,NaN,NaN,NaN,NaN,NaN,NaN
51522,NaN,NaN,NaN,NaN,NaN,NaN
51523,NaN,NaN,NaN,NaN,NaN,NaN
51524,NaN,NaN,NaN,NaN,NaN,NaN
51525,NaN,NaN,NaN,NaN,NaN,NaN
51526,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
최종병합_sub.loc[:, '동행한 사람과의 관계 친구/연인':'동행한 사람과의 관계 기타'] = \
    get_preprocessed_df(
        최종병합_sub.loc[:, '동행한 사람과의 관계 친구/연인':'동행한 사람과의 관계 기타'])

In [25]:
최종병합_sub.loc[:, '동행한 사람과의 관계 친구/연인':'동행한 사람과의 관계 기타']

,동행한 사람과의 관계 친구/연인,동행한 사람과의 관계 (직장)동료,동행한 사람과의 관계 단체/모임,동행한 사람과의 관계 비동거가족,동행한 사람과의 관계 친척,동행한 사람과의 관계 기타
0,1,0,0,0,0,0
1,1,0,0,0,0,0
2,0,0,0,0,0,0
3,0,0,1,0,0,0
4,0,0,1,0,0,0
5,0,0,1,0,0,0
6,0,0,1,0,0,0
7,0,0,1,0,0,0
8,0,0,1,0,0,0
9,0,0,0,1,0,0
10,1,0,0,0,0,0
11,1,0,0,0,0,0
12,1,0,0,0,0,0
13,0,0,0,1,0,0
14,0,0,0,1,0,0
15,0,0,0,1,0,0
16,1,0,0,0,0,0
17,1,0,0,0,0,0
18,0,0,0,0,0,0
19,0,0,1,0,0,0
20,1,0,0,0,0,0
21,0,0,0,1,0,1
22,0,0,0,1,0,1
23,1,0,0,0,0,0
24,1,0,0,0,0,0
25,0,0,0,0,0,0
26,0,0,0,0,0,0
27,1,0,0,0,0,0
28,1,0,0,0,0,0
29,0,0,0,0,0,0
...,...,...,...,...,...,...
51497,0,0,0,0,0,0
51498,0,0,0,0,0,0
51499,0,0,0,0,0,0
51500,0,0,0,0,0,0
51501,0,0,0,0,0,0
51502,0,0,0,0,0,0
51503,0,0,0,0,0,0
51504,0,0,0,0,0,0
51505,0,0,0,0,0,0
51506,0,0,0,0,0,0
51507,0,0,0,0,0,0
51508,0,0,0,0,0,0
51509,0,0,0,0,0,0
51510,0,0,0,0,0,0
51511,0,0,0,0,0,0
51512,0,0,0,0,0,0
51513,0,0,0,0,0,0
51514,0,0,0,0,0,0
51515,0,0,0,0,0,0
51516,0,0,0,0,0,0
51517,0,0,0,0,0,0
51518,0,0,0,0,0,0
51519,1,0,0,0,0,0
51520,0,0,0,0,0,0
51521,0,0,0,0,0,0
51522,0,0,0,0,0,0
51523,0,0,0,0,0,0
51524,0,0,0,0,0,0
51525,0,0,0,0,0,0
51526,0,0,0,0,0,0

In [26]:
최종병합_sub[[s for s in 최종병합_sub.columns if '여행지 선택이유' in s]]

       여행지 선택이유 1순위  여행지 선택이유 2순위  여행지 선택이유 3순위
0                 1           2.0           3.0
1                 1           2.0           3.0
2                 3           2.0           1.0
3                 2           1.0           7.0
4                 2           7.0           1.0
5                 1           2.0           7.0
6                 1           8.0           2.0
7                 1           4.0           7.0
8                 2           4.0           3.0
9                 7           1.0          10.0
10                2           1.0           4.0
11                1           2.0           5.0
12                1           2.0           5.0
13                7          15.0           NaN
14                1           2.0           5.0
15                1          10.0           5.0
16               12          15.0           NaN
17               12          15.0           NaN
18                7           4.0           1.0
19               15           NaN           NaN
20                9           1.0           7.0
21                1           5.0           7.0
22                1           5.0           7.0
23                7           2.0           1.0
24                1           7.0           2.0
25                1           2.0           7.0
26                7           1.0           2.0
27                1           7.0           2.0
28                1           2.0           3.0
29                7           1.0           2.0
...             ...           ...           ...
51497             3           4.0           7.0
51498             9           7.0           3.0
51499             7           1.0           2.0
51500             7           4.0          12.0
51501             4           7.0           9.0
51502             2           3.0           7.0
51503             1           2.0           7.0
51504             1           6.0           3.0
51505             1           6.0           3.0
51506             7          13.0           3.0
51507             2           7.0          13.0
51508             1           4.0           7.0
51509             4           7.0          13.0
51510             7          13.0           3.0
51511             7           1.0           2.0
51512             7          13.0           3.0
51513             2           7.0          13.0
51514             1           4.0           7.0
51515             4           7.0          13.0
51516             7           1.0           2.0
51517             7           1.0           2.0
51518             1           2.0           4.0
51519             5           1.0           2.0
51520             2           1.0           9.0
51521             2           1.0           9.0
51522             5           2.0           1.0
51523             2           9.0           1.0
51524             4           3.0           2.0
51525             4           1.0          12.0
51526             4           1.0          12.0

[51527 rows x 3 columns]

In [27]:
# 여행지 선택이유 2순위, 3순위 null값 컬럼 제거
# 2순위 null값 하나 제외하고 다 3순위 null값에 포함

pick_2 = set(최종병합_sub[(최종병합_sub['여행지 선택이유 2순위'].isnull())].index)
pick_3 = set(최종병합_sub[(최종병합_sub['여행지 선택이유 3순위'].isnull())].index)

print(len(pick_2), len(pick_3))
print(len(pick_2 & pick_3))
print(pick_2 - pick_3)

349 682
348
{43467}

In [28]:
# index 컬럼 왜 생겼지?? => 제거

최종병합_sub.drop('index', axis=1, inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [29]:
# 여행지 선택이유 2순위, 3순위 null값 컬럼 제거

최종병합_sub.drop(최종병합_sub.index[list(최종병합_sub.loc[pick_2 | pick_3].index)],
                inplace=True)

In [30]:
# 숙박시설 컬럼 OneHot 인코딩으로 처리

temp_df = 최종병합_sub[[s for s in 최종병합_sub.columns if '숙박시설' in s]]
temp_df.head()

,항목별 만족도 숙박시설,숙박시설 숙박하지 않음,숙박시설 호텔,숙박시설 콘도미니엄,숙박시설 유스호스텔,숙박시설 모텔/여관,숙박시설 펜션,숙박시설 민박,숙박시설 야영,숙박시설 자연휴양림 내 숙박시설,숙박시설 가족/친지집,숙박시설 연수원/수련원,숙박시설 전통한옥숙박시설,숙박시설 기타
0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
temp_df = get_preprocessed_df(temp_df)
temp_df

,항목별 만족도 숙박시설,숙박시설 숙박하지 않음,숙박시설 호텔,숙박시설 콘도미니엄,숙박시설 유스호스텔,숙박시설 모텔/여관,숙박시설 펜션,숙박시설 민박,숙박시설 야영,숙박시설 자연휴양림 내 숙박시설,숙박시설 가족/친지집,숙박시설 연수원/수련원,숙박시설 전통한옥숙박시설,숙박시설 기타
0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,1,0,0,0,0,0,0,0,0
5,0,1,0,0,0,0,0,0,0,0,0,0,0,0
6,0,1,0,0,0,0,0,0,0,0,0,0,0,0
7,0,1,0,0,0,0,0,0,0,0,0,0,0,0
8,0,1,0,0,0,0,0,0,0,0,0,0,0,0
9,0,1,0,0,0,0,0,0,0,0,0,0,0,0
10,1,0,0,1,0,0,0,0,0,0,0,0,0,0
11,1,0,0,0,0,0,0,0,0,0,1,0,0,0
12,1,0,0,0,0,0,1,0,0,0,0,0,0,0
14,1,0,0,0,0,0,1,0,0,0,0,0,0,0
15,1,0,0,0,0,0,1,0,0,0,0,0,0,0
18,1,0,0,0,0,0,0,0,1,0,0,0,0,0
20,0,1,0,0,0,0,0,0,0,0,0,0,0,0
21,1,0,0,0,0,0,0,0,0,0,0,0,0,1
22,1,0,0,0,0,0,1,0,0,0,0,0,0,0
23,1,0,0,1,0,0,0,0,0,0,0,0,0,0
24,1,0,0,0,0,0,0,1,0,0,0,0,0,0
25,1,0,0,0,0,0,1,0,0,0,0,0,0,0
26,1,0,0,0,0,0,1,0,0,0,0,0,0,0
27,1,0,0,0,0,0,0,0,0,0,0,1,0,0
28,1,0,0,0,0,0,1,0,0,0,0,0,0,0
29,1,0,0,0,0,0,1,0,0,0,0,0,0,0
30,1,0,0,0,0,0,0,0,0,0,0,1,0,0
31,1,0,0,0,0,0,0,0,0,0,1,0,0,0
32,1,0,0,0,0,0,0,1,0,0,0,0,0,0
33,1,0,0,0,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51497,1,0,0,1,0,0,0,0,0,0,0,0,0,0
51498,1,1,0,0,0,0,0,0,0,0,0,0,0,0
51499,1,1,0,0,0,0,0,0,0,0,0,0,0,0
51500,1,1,0,0,0,0,0,0,0,0,0,0,0,0
51501,1,1,0,0,0,0,0,0,0,0,0,0,0,0
51502,1,1,0,0,0,0,0,0,0,0,0,0,0,0
51503,1,0,0,0,1,0,0,0,0,0,0,0,0,0
51504,1,0,0,0,0,0,1,0,0,0,0,0,0,0
51505,1,0,0,0,0,0,1,0,0,0,0,0,0,0
51506,1,1,0,0,0,0,0,0,0,0,0,0,0,0
51507,1,0,0,0,0,1,0,0,0,0,0,0,0,0
51508,1,0,0,1,0,0,0,0,0,0,0,0,0,0
51509,1,1,0,0,0,0,0,0,0,0,0,0,0,0
51510,1,1,0,0,0,0,0,0,0,0,0,0,0,0
51511,1,1,0,0,0,0,0,0,0,0,0,0,0,0
51512,1,1,0,0,0,0,0,0,0,0,0,0,0,0
51513,1,0,0,0,0,1,0,0,0,0,0,0,0,0
51514,1,0,0,1,0,0,0,0,0,0,0,0,0,0
51515,1,1,0,0,0,0,0,0,0,0,0,0,0,0
51516,1,1,0,0,0,0,0,0,0,0,0,0,0,0
51517,1,0,0,0,0,0,0,0,0,0,1,0,0,0
51518,1,1,0,0,0,0,0,0,0,0,0,0,0,0
51519,1,0,0,0,0,0,0,0,0,0,0,1,0,0
51520,1,0,0,0,0,0,1,0,0,0,0,0,0,0
51521,1,0,0,0,0,0,0,0,1,0,0,0,0,0
51522,1,0,0,0,0,0,1,0,0,0,0,0,0,0
51523,1,1,0,0,0,0,0,0,0,0,0,0,0,0
51524,1,1,0,0,0,0,0,0,0,0,0,0,0,0
51525,1,0,1,0,0,0,0,0,0,0,0,0,0,0
51526,1,0,1,0,0,0,0,0,0,0,0,0,0,0

In [32]:
최종병합_sub[[s for s in 최종병합_sub.columns if '숙박시설' in s]] = temp_df
최종병합_sub.info()

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50844 entries, 0 to 51526
Data columns (total 93 columns):
gubun                             50844 non-null int64
가구번호                              50844 non-null int64
가구원번호                             50844 non-null int64
매칭 ID                             50844 non-null int64
당일/숙박여행 여부                        50844 non-null int64
여행 출발 월                           50844 non-null int64
여행 출발 일                           50844 non-null int64
여행 박                              50844 non-null int64
여행 시기 주중                          50844 non-null int64
여행 시기 주말                          50844 non-null int64
여행 시기 휴가/방학                       50844 non-null int64
여행 시기 설날/추석                       50844 non-null int64
여행 시기 공휴일                         50844 non-null int64
여행 주 목적                           50844 non-null int64
여행 정보 주요 획득지 1순위                  50844 non-null int64
여행 정보 주요 획득지 2순위                  43921 non-null float64
함께 여행한 일행 존재 여부                   50844 non-null int64
본인을 제외한 함께 여행한 일행 수               50844 non-null int64
동행한 사람과의 관계 친구/연인                 50844 non-null int64
동행한 사람과의 관계 (직장)동료                50844 non-null int64
동행한 사람과의 관계 단체/모임                 50844 non-null int64
동행한 사람과의 관계 비동거가족                 50844 non-null int64
동행한 사람과의 관계 친척                    50844 non-null int64
동행한 사람과의 관계 기타                    50844 non-null int64
총 지출비용                            50844 non-null int64
사전 지출비용                           50844 non-null int64
단체비용                              25575 non-null float64
여행사 상품구입비                         50844 non-null int64
숙박비                               50844 non-null int64
교통비                               50844 non-null int64
식/음료비                             50844 non-null int64
문화/오락시설 이용료/관람료                   50844 non-null int64
스포츠/레포츠 용품대여/구입비, 경기관람료           50844 non-null int64
기념품 및 쇼핑비                         50844 non-null int64
여행지에서 여행관련용품 구입비                  50844 non-null int64
기타비용                              50844 non-null int64
여행 출발 전 사전예약을 통해 이용한 서비스 여부       50844 non-null int64
여행상품 구매 또는 이용 여부                  50844 non-null int64
항목별 만족도 자연경관                      50844 non-null int64
항목별 만족도 문화유산                      50843 non-null float64
항목별 만족도 교통                        50844 non-null int64
항목별 만족도 숙박시설                      50844 non-null int64
항목별 만족도 식당 및 음식                   50844 non-null int64
항목별 만족도 쇼핑                        50842 non-null float64
항목별 만족도 관광정보 및 안내시설               50844 non-null int64
항목별 만족도 관광지 편의시설                  50844 non-null int64
항목별 만족도 지역 관광종사자의 친절성             50844 non-null int64
항목별 만족도 체험프로그램                    50844 non-null int64
항목별 만족도 관광지 물가                    50844 non-null int64
항목별 만족도 관광지 혼잡도                   50844 non-null int64
여행한 광역시/도(해외여행: 국가)               50844 non-null int64
여행한 광역시/도 내 시/군1(해외여행: 도시)        50844 non-null int64
여행지 선택이유 1순위                      50844 non-null int64
여행지 선택이유 2순위                      50844 non-null float64
여행지 선택이유 3순위                      50844 non-null float64
주요 이동(교통)수단                       50844 non-null int64
전반적 만족도                           50844 non-null int64
재방문 의향                            50844 non-null int64
타인 추천의향                           50844 non-null int64
숙박시설 숙박하지 않음                      50844 non-null int64
숙박시설 호텔                           50844 non-null int64
숙박시설 콘도미니엄                        50844 non-null int64
숙박시설 유스호스텔                        50844 non-null int64
숙박시설 모텔/여관                        50844 non-null int64
숙박시설 펜션                           50844 non-null int64
숙박시설 민박                           50844 non-null int64
숙박시설 야영                           50844 non-null int64
숙박시설 자연휴양림 내 숙박시설                 50844 non-null int64
숙박시설 가족/친지집                       50844 non-null int64
숙박시설 연수원/수련원                      50844 non-null int64
숙박시설 전통한옥숙박시설                     50844 non-null int64
숙박시설 기타                           50844 non-null int64
여행지에서의 활동 자연 및 풍경 감상              41370 non-null float64
여행지에서의 활동 음식관광                    28978 non-null float64
여행지에서의 활동 야외 위락 및 스포츠 활동          16567 non-null float64
여행지에서의 활동 역사유적지 방문                6661 non-null float64
여행지에서의 활동 테마파크, 놀이시설, 동/식물원 방문    6563 non-null float64
여행지에서의 활동 휴식/휴양                   20994 non-null float64
여행지에서의 활동 온천/스파                   1985 non-null float64
여행지에서의 활동 쇼핑                      2567 non-null float64
여행지에서의 활동 지역 문화예술/공연/전시시설 관람      3809 non-null float64
여행지에서의 활동 스포츠 경기 관람               739 non-null float64
여행지에서의 활동 지역 축제/이벤트 참가            2630 non-null float64
여행지에서의 활동 교육/체험프로그램 참가            1485 non-null float64
여행지에서의 활동 종교/성지순례                 1859 non-null float64
여행지에서의 활동 갬블링                     21 non-null float64
여행지에서의 활동 시티투어                    414 non-null float64
여행지에서의 활동 드라마 촬영지 방문              524 non-null float64
여행지에서의 활동 가족/친지/친구 방문             2120 non-null float64
여행지에서의 활동 회의참가/시찰                 96 non-null float64
여행지에서의 활동 교육/훈련/연수                278 non-null float64
여행지에서의 활동 유흥/오락                   1489 non-null float64
여행지에서의 활동 기타                      1933 non-null float64
dtypes: float64(27), int64(66)
memory usage: 36.5 MB

In [33]:
# 여행지에서의 활동 컬럼 OneHot 인코딩으로 처리

temp_df = 최종병합_sub[[s for s in 최종병합_sub.columns if '여행지에서의 활동' in s]]
temp_df.head()

,여행지에서의 활동 자연 및 풍경 감상,여행지에서의 활동 음식관광,여행지에서의 활동 야외 위락 및 스포츠 활동,여행지에서의 활동 역사유적지 방문,"여행지에서의 활동 테마파크, 놀이시설, 동/식물원 방문",여행지에서의 활동 휴식/휴양,여행지에서의 활동 온천/스파,여행지에서의 활동 쇼핑,여행지에서의 활동 지역 문화예술/공연/전시시설 관람,여행지에서의 활동 스포츠 경기 관람,...,여행지에서의 활동 교육/체험프로그램 참가,여행지에서의 활동 종교/성지순례,여행지에서의 활동 갬블링,여행지에서의 활동 시티투어,여행지에서의 활동 드라마 촬영지 방문,여행지에서의 활동 가족/친지/친구 방문,여행지에서의 활동 회의참가/시찰,여행지에서의 활동 교육/훈련/연수,여행지에서의 활동 유흥/오락,여행지에서의 활동 기타
0,1.0,2.0,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,2.0,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,9.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
temp_df = get_preprocessed_df(temp_df)
temp_df

,여행지에서의 활동 자연 및 풍경 감상,여행지에서의 활동 음식관광,여행지에서의 활동 야외 위락 및 스포츠 활동,여행지에서의 활동 역사유적지 방문,"여행지에서의 활동 테마파크, 놀이시설, 동/식물원 방문",여행지에서의 활동 휴식/휴양,여행지에서의 활동 온천/스파,여행지에서의 활동 쇼핑,여행지에서의 활동 지역 문화예술/공연/전시시설 관람,여행지에서의 활동 스포츠 경기 관람,...,여행지에서의 활동 교육/체험프로그램 참가,여행지에서의 활동 종교/성지순례,여행지에서의 활동 갬블링,여행지에서의 활동 시티투어,여행지에서의 활동 드라마 촬영지 방문,여행지에서의 활동 가족/친지/친구 방문,여행지에서의 활동 회의참가/시찰,여행지에서의 활동 교육/훈련/연수,여행지에서의 활동 유흥/오락,여행지에서의 활동 기타
0,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
7,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,1,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,1,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,1,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,1,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,1,1,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,1,1,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,1,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,1,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51497,1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
51498,1,1,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
51499,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
51500,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51501,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51502,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
51503,1,1,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
51504,1,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51505,1,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51506,1,1,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
51507,1,1,1,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
51508,1,1,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
51509,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
51510,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
51511,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
51512,1,1,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
51513,1,1,1,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
51514,1,1,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
51515,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
51516,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
51517,1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
51518,0,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
51519,0,1,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
51520,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51521,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51522,1,1,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
51523,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51524,1,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51525,1,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
51526,1,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [35]:
최종병합_sub[[s for s in 최종병합_sub.columns if '여행지에서의 활동' in s]] = temp_df
최종병합_sub.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50844 entries, 0 to 51526
Data columns (total 93 columns):
gubun                             50844 non-null int64
가구번호                              50844 non-null int64
가구원번호                             50844 non-null int64
매칭 ID                             50844 non-null int64
당일/숙박여행 여부                        50844 non-null int64
여행 출발 월                           50844 non-null int64
여행 출발 일                           50844 non-null int64
여행 박                              50844 non-null int64
여행 시기 주중                          50844 non-null int64
여행 시기 주말                          50844 non-null int64
여행 시기 휴가/방학                       50844 non-null int64
여행 시기 설날/추석                       50844 non-null int64
여행 시기 공휴일                         50844 non-null int64
여행 주 목적                           50844 non-null int64
여행 정보 주요 획득지 1순위                  50844 non-null int64
여행 정보 주요 획득지 2순위                  43921 non-null float64
함께 여행한 일행 존재 여부                   50844 non-null int64
본인을 제외한 함께 여행한 일행 수               50844 non-null int64
동행한 사람과의 관계 친구/연인                 50844 non-null int64
동행한 사람과의 관계 (직장)동료                50844 non-null int64
동행한 사람과의 관계 단체/모임                 50844 non-null int64
동행한 사람과의 관계 비동거가족                 50844 non-null int64
동행한 사람과의 관계 친척                    50844 non-null int64
동행한 사람과의 관계 기타                    50844 non-null int64
총 지출비용                            50844 non-null int64
사전 지출비용                           50844 non-null int64
단체비용                              25575 non-null float64
여행사 상품구입비                         50844 non-null int64
숙박비                               50844 non-null int64
교통비                               50844 non-null int64
식/음료비                             50844 non-null int64
문화/오락시설 이용료/관람료                   50844 non-null int64
스포츠/레포츠 용품대여/구입비, 경기관람료           50844 non-null int64
기념품 및 쇼핑비                         50844 non-null int64
여행지에서 여행관련용품 구입비                  50844 non-null int64
기타비용                              50844 non-null int64
여행 출발 전 사전예약을 통해 이용한 서비스 여부       50844 non-null int64
여행상품 구매 또는 이용 여부                  50844 non-null int64
항목별 만족도 자연경관                      50844 non-null int64
항목별 만족도 문화유산                      50843 non-null float64
항목별 만족도 교통                        50844 non-null int64
항목별 만족도 숙박시설                      50844 non-null int64
항목별 만족도 식당 및 음식                   50844 non-null int64
항목별 만족도 쇼핑                        50842 non-null float64
항목별 만족도 관광정보 및 안내시설               50844 non-null int64
항목별 만족도 관광지 편의시설                  50844 non-null int64
항목별 만족도 지역 관광종사자의 친절성             50844 non-null int64
항목별 만족도 체험프로그램                    50844 non-null int64
항목별 만족도 관광지 물가                    50844 non-null int64
항목별 만족도 관광지 혼잡도                   50844 non-null int64
여행한 광역시/도(해외여행: 국가)               50844 non-null int64
여행한 광역시/도 내 시/군1(해외여행: 도시)        50844 non-null int64
여행지 선택이유 1순위                      50844 non-null int64
여행지 선택이유 2순위                      50844 non-null float64
여행지 선택이유 3순위                      50844 non-null float64
주요 이동(교통)수단                       50844 non-null int64
전반적 만족도                           50844 non-null int64
재방문 의향                            50844 non-null int64
타인 추천의향                           50844 non-null int64
숙박시설 숙박하지 않음                      50844 non-null int64
숙박시설 호텔                           50844 non-null int64
숙박시설 콘도미니엄                        50844 non-null int64
숙박시설 유스호스텔                        50844 non-null int64
숙박시설 모텔/여관                        50844 non-null int64
숙박시설 펜션                           50844 non-null int64
숙박시설 민박                           50844 non-null int64
숙박시설 야영                           50844 non-null int64
숙박시설 자연휴양림 내 숙박시설                 50844 non-null int64
숙박시설 가족/친지집                       50844 non-null int64
숙박시설 연수원/수련원                      50844 non-null int64
숙박시설 전통한옥숙박시설                     50844 non-null int64
숙박시설 기타                           50844 non-null int64
여행지에서의 활동 자연 및 풍경 감상              50844 non-null int64
여행지에서의 활동 음식관광                    50844 non-null int64
여행지에서의 활동 야외 위락 및 스포츠 활동          50844 non-null int64
여행지에서의 활동 역사유적지 방문                50844 non-null int64
여행지에서의 활동 테마파크, 놀이시설, 동/식물원 방문    50844 non-null int64
여행지에서의 활동 휴식/휴양                   50844 non-null int64
여행지에서의 활동 온천/스파                   50844 non-null int64
여행지에서의 활동 쇼핑                      50844 non-null int64
여행지에서의 활동 지역 문화예술/공연/전시시설 관람      50844 non-null int64
여행지에서의 활동 스포츠 경기 관람               50844 non-null int64
여행지에서의 활동 지역 축제/이벤트 참가            50844 non-null int64
여행지에서의 활동 교육/체험프로그램 참가            50844 non-null int64
여행지에서의 활동 종교/성지순례                 50844 non-null int64
여행지에서의 활동 갬블링                     50844 non-null int64
여행지에서의 활동 시티투어                    50844 non-null int64
여행지에서의 활동 드라마 촬영지 방문              50844 non-null int64
여행지에서의 활동 가족/친지/친구 방문             50844 non-null int64
여행지에서의 활동 회의참가/시찰                 50844 non-null int64
여행지에서의 활동 교육/훈련/연수                50844 non-null int64
여행지에서의 활동 유흥/오락                   50844 non-null int64
여행지에서의 활동 기타                      50844 non-null int64
dtypes: float64(6), int64(87)
memory usage: 36.5 MB

In [36]:
# 인덱스 초기화

최종병합_sub.reset_index(inplace=True)

In [37]:
최종병합_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50844 entries, 0 to 50843
Data columns (total 94 columns):
index                             50844 non-null int64
gubun                             50844 non-null int64
가구번호                              50844 non-null int64
가구원번호                             50844 non-null int64
매칭 ID                             50844 non-null int64
당일/숙박여행 여부                        50844 non-null int64
여행 출발 월                           50844 non-null int64
여행 출발 일                           50844 non-null int64
여행 박                              50844 non-null int64
여행 시기 주중                          50844 non-null int64
여행 시기 주말                          50844 non-null int64
여행 시기 휴가/방학                       50844 non-null int64
여행 시기 설날/추석                       50844 non-null int64
여행 시기 공휴일                         50844 non-null int64
여행 주 목적                           50844 non-null int64
여행 정보 주요 획득지 1순위                  50844 non-null int64
여행 정보 주요 획득지 2순위                  43921 non-null float64
함께 여행한 일행 존재 여부                   50844 non-null int64
본인을 제외한 함께 여행한 일행 수               50844 non-null int64
동행한 사람과의 관계 친구/연인                 50844 non-null int64
동행한 사람과의 관계 (직장)동료                50844 non-null int64
동행한 사람과의 관계 단체/모임                 50844 non-null int64
동행한 사람과의 관계 비동거가족                 50844 non-null int64
동행한 사람과의 관계 친척                    50844 non-null int64
동행한 사람과의 관계 기타                    50844 non-null int64
총 지출비용                            50844 non-null int64
사전 지출비용                           50844 non-null int64
단체비용                              25575 non-null float64
여행사 상품구입비                         50844 non-null int64
숙박비                               50844 non-null int64
교통비                               50844 non-null int64
식/음료비                             50844 non-null int64
문화/오락시설 이용료/관람료                   50844 non-null int64
스포츠/레포츠 용품대여/구입비, 경기관람료           50844 non-null int64
기념품 및 쇼핑비                         50844 non-null int64
여행지에서 여행관련용품 구입비                  50844 non-null int64
기타비용                              50844 non-null int64
여행 출발 전 사전예약을 통해 이용한 서비스 여부       50844 non-null int64
여행상품 구매 또는 이용 여부                  50844 non-null int64
항목별 만족도 자연경관                      50844 non-null int64
항목별 만족도 문화유산                      50843 non-null float64
항목별 만족도 교통                        50844 non-null int64
항목별 만족도 숙박시설                      50844 non-null int64
항목별 만족도 식당 및 음식                   50844 non-null int64
항목별 만족도 쇼핑                        50842 non-null float64
항목별 만족도 관광정보 및 안내시설               50844 non-null int64
항목별 만족도 관광지 편의시설                  50844 non-null int64
항목별 만족도 지역 관광종사자의 친절성             50844 non-null int64
항목별 만족도 체험프로그램                    50844 non-null int64
항목별 만족도 관광지 물가                    50844 non-null int64
항목별 만족도 관광지 혼잡도                   50844 non-null int64
여행한 광역시/도(해외여행: 국가)               50844 non-null int64
여행한 광역시/도 내 시/군1(해외여행: 도시)        50844 non-null int64
여행지 선택이유 1순위                      50844 non-null int64
여행지 선택이유 2순위                      50844 non-null float64
여행지 선택이유 3순위                      50844 non-null float64
주요 이동(교통)수단                       50844 non-null int64
전반적 만족도                           50844 non-null int64
재방문 의향                            50844 non-null int64
타인 추천의향                           50844 non-null int64
숙박시설 숙박하지 않음                      50844 non-null int64
숙박시설 호텔                           50844 non-null int64
숙박시설 콘도미니엄                        50844 non-null int64
숙박시설 유스호스텔                        50844 non-null int64
숙박시설 모텔/여관                        50844 non-null int64
숙박시설 펜션                           50844 non-null int64
숙박시설 민박                           50844 non-null int64
숙박시설 야영                           50844 non-null int64
숙박시설 자연휴양림 내 숙박시설                 50844 non-null int64
숙박시설 가족/친지집                       50844 non-null int64
숙박시설 연수원/수련원                      50844 non-null int64
숙박시설 전통한옥숙박시설                     50844 non-null int64
숙박시설 기타                           50844 non-null int64
여행지에서의 활동 자연 및 풍경 감상              50844 non-null int64
여행지에서의 활동 음식관광                    50844 non-null int64
여행지에서의 활동 야외 위락 및 스포츠 활동          50844 non-null int64
여행지에서의 활동 역사유적지 방문                50844 non-null int64
여행지에서의 활동 테마파크, 놀이시설, 동/식물원 방문    50844 non-null int64
여행지에서의 활동 휴식/휴양                   50844 non-null int64
여행지에서의 활동 온천/스파                   50844 non-null int64
여행지에서의 활동 쇼핑                      50844 non-null int64
여행지에서의 활동 지역 문화예술/공연/전시시설 관람      50844 non-null int64
여행지에서의 활동 스포츠 경기 관람               50844 non-null int64
여행지에서의 활동 지역 축제/이벤트 참가            50844 non-null int64
여행지에서의 활동 교육/체험프로그램 참가            50844 non-null int64
여행지에서의 활동 종교/성지순례                 50844 non-null int64
여행지에서의 활동 갬블링                     50844 non-null int64
여행지에서의 활동 시티투어                    50844 non-null int64
여행지에서의 활동 드라마 촬영지 방문              50844 non-null int64
여행지에서의 활동 가족/친지/친구 방문             50844 non-null int64
여행지에서의 활동 회의참가/시찰                 50844 non-null int64
여행지에서의 활동 교육/훈련/연수                50844 non-null int64
여행지에서의 활동 유흥/오락                   50844 non-null int64
여행지에서의 활동 기타                      50844 non-null int64
dtypes: float64(6), int64(88)
memory usage: 36.5 MB

In [38]:
최종병합_sub.to_csv('C:/Users/user/Desktop/kdata/프로젝트/최종병합_preprocessed1.csv', encoding='cp949')

# what is mathing ID?

매칭 아이디는 기본적으로 하나의 여행에 한 개씩 부여됨

그러나 한 여행에 여러 도를 다닌 경우(여행한 광역시/도(해외여행: 국가) 컬럼의 코드가 다른 경우)에는 
다른 row로 분리되어 동일한 가구원이 여러 개의 매칭 아이디를 가지기도 함

15년도 데이터에는 매칭 아이디가 따로 부여되지 않았으며 '여행 월'과 '여행 번째'로 단위 여행이 구분됨

그러나 16년도, 17년도 데이터와 병합하는 과정에서 '여행 번째'를 '매칭 ID'로 바꾸었음. (컬럼명 통일을 위해서)

따라서 단위여행을 구분하기 위해서는 '매칭 ID'와 '여행 월'을 같이 봐야 함

# 도시코드 unique하게 수정

In [41]:
# 여행한 광역시/도 내 시/군1 컬럼 변경
# '여행한 광역시/도(헤외여행: 국가)', '여행한 광역시/도 내 시/군1(해외여행: 도시)' 코드 합치기

temp_sr_1 = 최종병합_sub['여행한 광역시/도 내 시/군1(해외여행: 도시)'].astype(int).apply(
    lambda s: str(s) if len(str(s))!=2 else '0'+str(s))

temp_sr_2 = 최종병합_sub['여행한 광역시/도(해외여행: 국가)'].astype(int).astype(str) 

최종병합_sub['여행한 광역시/도 내 시/군1(해외여행: 도시)'] = temp_sr_2 + temp_sr_1

최종병합_sub['여행한 광역시/도 내 시/군1(해외여행: 도시)'].value_counts(ascending=False)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

939020    1722
932060    1366
921090    1261
937020    1151
931370    1037
936020     972
932030     893
931190     820
934030     803
935010     763
934380     754
938050     741
931380     724
938090     698
936030     691
923310     636
932010     604
931270     592
934040     573
939010     539
937010     530
911010     507
932310     501
923010     498
938350     497
932340     480
931010     458
911230     456
911240     448
935020     443
          ...
937400      43
923070      40
911200      39
926010      36
924030      36
911040      35
931080      33
937320      33
923060      32
922050      32
911150      32
911160      32
931160      31
938310      29
923030      29
932380      26
937370      25
921130      24
911170      23
911250      23
923020      20
931120      19
921080      18
921030      18
934320      17
933390      16
911180      15
911070      13
922030      13
937340      12
Name: 여행한 광역시/도 내 시/군1(해외여행: 도시), Length: 231, dtype: int64

In [42]:
# 도시 한글 이름 추가

도시코드 = pd.read_csv('C:/Users/user/Desktop/kdata/프로젝트/도시코드.csv', encoding = 'utf-8')

temp_sr_1 = 도시코드['여행한 광역시/도 내 시/군1(해외여행: 도시)'].astype(int).apply(
    lambda s: str(s) if len(str(s))!=2 else '0'+str(s))

temp_sr_2 = 도시코드['여행한 광역시/도(해외여행: 국가)'].astype(int).astype(str) 

도시코드['여행한 광역시/도 내 시/군1(해외여행: 도시)'] = temp_sr_2 + temp_sr_1

도시코드['여행한 광역시/도 내 시/군1(해외여행: 도시)'].value_counts(ascending=False)

931020    1
921090    1
937010    1
925050    1
936480    1
937050    1
922010    1
935370    1
938050    1
937060    1
931320    1
911130    1
938360    1
931050    1
931180    1
933380    1
931060    1
921120    1
931370    1
911240    1
937410    1
923310    1
926310    1
931040    1
926020    1
936410    1
936310    1
938080    1
935030    1
931170    1
         ..
935320    1
932310    1
923020    1
932330    1
921110    1
933350    1
911190    1
937400    1
934080    1
935060    1
937360    1
936060    1
925030    1
931240    1
931120    1
937080    1
933370    1
911250    1
934020    1
935040    1
937090    1
937070    1
937340    1
925040    1
936030    1
926030    1
931030    1
934380    1
911140    1
935050    1
Name: 여행한 광역시/도 내 시/군1(해외여행: 도시), Length: 231, dtype: int64

In [43]:
도시코드 = 도시코드.iloc[:, 0:4]

In [44]:
도시코드.head()

   시도   군구  여행한 광역시/도(해외여행: 국가) 여행한 광역시/도 내 시/군1(해외여행: 도시)
0  서울  종로구                  911                     911010
1  서울   중구                  911                     911020
2  서울  용산구                  911                     911030
3  서울  성동구                  911                     911040
4  서울  광진구                  911                     911050

In [45]:
최종병합_sub = pd.merge(최종병합_sub, 도시코드, 
                      on = ['여행한 광역시/도(해외여행: 국가)', '여행한 광역시/도 내 시/군1(해외여행: 도시)'])

In [46]:
최종병합_sub.head()

,index,gubun,가구번호,가구원번호,매칭 ID,당일/숙박여행 여부,여행 출발 월,여행 출발 일,여행 박,여행 시기 주중,...,여행지에서의 활동 갬블링,여행지에서의 활동 시티투어,여행지에서의 활동 드라마 촬영지 방문,여행지에서의 활동 가족/친지/친구 방문,여행지에서의 활동 회의참가/시찰,여행지에서의 활동 교육/훈련/연수,여행지에서의 활동 유흥/오락,여행지에서의 활동 기타,시도,군구
0,0,2,10007,1000701,1,1,11,5,0,1,...,0,0,0,0,0,0,0,0,전북,정읍시
1,1,2,10007,1000701,2,1,11,5,0,1,...,0,0,0,0,0,0,0,0,전북,정읍시
2,2,1,10007,1000701,1,1,10,8,0,1,...,0,0,0,0,0,0,0,0,전북,정읍시
3,140,1,10081,1008101,701,1,10,8,0,1,...,0,0,0,0,0,0,0,0,전북,정읍시
4,191,2,10129,1012902,1,1,10,10,0,0,...,0,0,0,0,0,0,0,0,전북,정읍시

In [47]:
# 인덱스 컬럼 삭제

최종병합_sub.drop('index', axis = 1, inplace = True)

In [49]:
최종병합_sub.to_csv('C:/Users/user/Desktop/kdata/프로젝트/최종병합_전처리2차.csv', encoding='cp949')